# SIMON'S MOCK UP

### FIRST I IMPORT LIBRARIES

In [1]:
import pandas as pd 
import numpy as np

### THEN I IMPORT AND READ ORIGINAL AVIATION DATA CSV FILE.

### THEN I LIST COLUMNS

In [2]:
df = pd.read_csv('data/AviationData.csv', encoding = "ISO-8859-1")

df.columns.tolist()

C:\Users\simon\anaconda3\envs\learn-env\lib\site-packages\IPython\core\interactiveshell.py:3145: DtypeWarning: Columns (6,7,28) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

['Event.Id',
 'Investigation.Type',
 'Accident.Number',
 'Event.Date',
 'Location',
 'Country',
 'Latitude',
 'Longitude',
 'Airport.Code',
 'Airport.Name',
 'Injury.Severity',
 'Aircraft.damage',
 'Aircraft.Category',
 'Registration.Number',
 'Make',
 'Model',
 'Amateur.Built',
 'Number.of.Engines',
 'Engine.Type',
 'FAR.Description',
 'Schedule',
 'Purpose.of.flight',
 'Air.carrier',
 'Total.Fatal.Injuries',
 'Total.Serious.Injuries',
 'Total.Minor.Injuries',
 'Total.Uninjured',
 'Weather.Condition',
 'Broad.phase.of.flight',
 'Report.Status',
 'Publication.Date']

## .SHAPE, .HEAD(), .INFO(), .DESCRIBE()

In [4]:
df.shape

(88889, 31)

In [14]:
# Show all columns by disabling truncation
pd.set_option('display.max_columns', None)

# Disable column-wise line wrapping
pd.set_option('display.expand_frame_repr', False)

df.head()

         Event.Id Investigation.Type Accident.Number  Event.Date         Location        Country Latitude Longitude Airport.Code Airport.Name Injury.Severity Aircraft.damage Aircraft.Category Registration.Number      Make     Model Amateur.Built  Number.of.Engines    Engine.Type FAR.Description Schedule Purpose.of.flight Air.carrier  Total.Fatal.Injuries  Total.Serious.Injuries  Total.Minor.Injuries  Total.Uninjured Weather.Condition Broad.phase.of.flight   Report.Status Publication.Date
0  20001218X45444           Accident      SEA87LA080  1948-10-24  MOOSE CREEK, ID  United States      NaN       NaN          NaN          NaN        Fatal(2)       Destroyed               NaN              NC6404   Stinson     108-3            No                1.0  Reciprocating             NaN      NaN          Personal         NaN                   2.0                     0.0                   0.0              0.0               UNK                Cruise  Probable Cause              NaN
1  20001218X45447           Accident      LAX94LA336  1962-07-19   BRIDGEPORT, CA  United States      NaN       NaN          NaN          NaN        Fatal(4)       Destroyed               NaN              N5069P     Piper  PA24-180            No                1.0  Reciprocating             NaN      NaN          Personal         NaN                   4.0                     0.0                   0.0              0.0               UNK               Unknown  Probable Cause       19-09-1996
2  20061025X01555           Accident      NYC07LA005  1974-08-30    Saltville, VA  United States  36.9222  -81.8781          NaN          NaN        Fatal(3)       Destroyed               NaN              N5142R    Cessna      172M            No                1.0  Reciprocating             NaN      NaN          Personal         NaN                   3.0                     NaN                   NaN              NaN               IMC                Cruise  Probable Cause       26-02-2007
3  20001218X45448           Accident      LAX96LA321  1977-06-19       EUREKA, CA  United States      NaN       NaN          NaN          NaN        Fatal(2)       Destroyed               NaN              N1168J  Rockwell       112            No                1.0  Reciprocating             NaN      NaN          Personal         NaN                   2.0                     0.0                   0.0              0.0               IMC                Cruise  Probable Cause       12-09-2000
4  20041105X01764           Accident      CHI79FA064  1979-08-02       Canton, OH  United States      NaN       NaN          NaN          NaN        Fatal(1)       Destroyed               NaN               N15NY    Cessna       501            No                NaN            NaN             NaN      NaN          Personal         NaN                   1.0                     2.0                   NaN              0.0               VMC              Approach  Probable Cause       16-04-1980

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88889 entries, 0 to 88888
Data columns (total 31 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Event.Id                88889 non-null  object
 1   Investigation.Type      88889 non-null  object
 2   Accident.Number         88889 non-null  object
 3   Event.Date              88889 non-null  object
 4   Location                88837 non-null  object
 5   Country                 88663 non-null  object
 6   Latitude                34382 non-null  object
 7   Longitude               34373 non-null  object
 8   Airport.Code            50249 non-null  object
 9   Airport.Name            52790 non-null  object
 10  Injury.Severity         87889 non-null  object
 11  Aircraft.damage         85695 non-null  object
 12  Aircraft.Category       32287 non-null  object
 13  Registration.Number     87572 non-null  object
 14  Make                    88826 non-null  object
 15  Model                   88797 non-null  object
 16  Amateur.Built           88787 non-null  object
 17  Number.of.Engines       82805 non-null  float64
 18  Engine.Type             81812 non-null  object
 19  FAR.Description         32023 non-null  object
 20  Schedule                12582 non-null  object
 21  Purpose.of.flight       82697 non-null  object
 22  Air.carrier             16648 non-null  object
 23  Total.Fatal.Injuries    77488 non-null  float64
 24  Total.Serious.Injuries  76379 non-null  float64
 25  Total.Minor.Injuries    76956 non-null  float64
 26  Total.Uninjured         82977 non-null  float64
 27  Weather.Condition       84397 non-null  object
 28  Broad.phase.of.flight   61724 non-null  object
 29  Report.Status           82508 non-null  object
 30  Publication.Date        75118 non-null  object
dtypes: float64(5), object(26)
memory usage: 21.0+ MB

In [24]:
df.describe()

       Number.of.Engines  Total.Fatal.Injuries  Total.Serious.Injuries  Total.Minor.Injuries  Total.Uninjured
count       82805.000000          77488.000000            76379.000000          76956.000000     82977.000000
mean            1.146585              0.647855                0.279881              0.357061         5.325440
std             0.446510              5.485960                1.544084              2.235625        27.913634
min             0.000000              0.000000                0.000000              0.000000         0.000000
25%             1.000000              0.000000                0.000000              0.000000         0.000000
50%             1.000000              0.000000                0.000000              0.000000         1.000000
75%             1.000000              0.000000                0.000000              0.000000         2.000000
max             8.000000            349.000000              161.000000            380.000000       699.000000

### HERE I RETRIEVED ALL INPUTS FROM EACH COLUMN BUT ONLY IF NUMBER OF UNIQUE INPUTS FOR COLUMN <= 30 (JUST FOR FUNSIES)

In [38]:
max_unique_threshold = 30

for column in df.columns:
    unique_values = df[column].unique()
    if len(unique_values) <= max_unique_threshold: 
        print(f'Column: {column}')
        print('Unique Values:')
        for value in unique_values:
              print(value)
        print()

Column: Investigation.Type
Unique Values:
Accident
Incident

Column: Aircraft.damage
Unique Values:
Destroyed
Substantial
Minor
nan
Unknown

Column: Aircraft.Category
Unique Values:
nan
Airplane
Helicopter
Glider
Balloon
Gyrocraft
Ultralight
Unknown
Blimp
Powered-Lift
Weight-Shift
Powered Parachute
Rocket
WSFT
UNK
ULTR

Column: Amateur.Built
Unique Values:
No
Yes
nan

Column: Number.of.Engines
Unique Values:
1.0
nan
2.0
0.0
3.0
4.0
8.0
6.0

Column: Engine.Type
Unique Values:
Reciprocating
nan
Turbo Fan
Turbo Shaft
Unknown
Turbo Prop
Turbo Jet
None
Electric
Hybrid Rocket
Geared Turbofan
LR
NONE
UNK

Column: Schedule
Unique Values:
nan
SCHD
NSCH
UNK

Column: Purpose.of.flight
Unique Values:
Personal
nan
Business
Instructional
Unknown
Ferry
Executive/corporate
Aerial Observation
Aerial Application
Public Aircraft
Skydiving
Other Work Use
Positioning
Flight Test
Air Race/show
Air Drop
Public Aircraft - Federal
Glider Tow
Public Aircraft - Local
External Load
Public Aircraft - State
Banner Tow
Firefighting
Air Race show
PUBS
ASHO
PUBL

Column: Weather.Condition
Unique Values:
UNK
IMC
VMC
nan
Unk

Column: Broad.phase.of.flight
Unique Values:
Cruise
Unknown
Approach
Climb
Takeoff
Landing
Taxi
Descent
Maneuvering
Standing
Go-around
Other
nan

### HERE I SORTED THE EVENT DATES SO I CAN SEE THE EARLIEST LISTING OF A CRASH

In [16]:
column_name = 'Event.Date'

earliest_elements = df.sort_values(column_name)[column_name].head(5)

earliest_elements

0    1948-10-24
1    1962-07-19
2    1974-08-30
3    1977-06-19
4    1979-08-02
Name: Event.Date, dtype: object

In [17]:
index_of_interest = 0

row_of_interest = df.loc[index_of_interest]

print("Row of interest:")
print(row_of_interest)

Row of interest:
Event.Id                   20001218X45444
Investigation.Type               Accident
Accident.Number                SEA87LA080
Event.Date                     1948-10-24
Location                  MOOSE CREEK, ID
Country                     United States
Latitude                              NaN
Longitude                             NaN
Airport.Code                          NaN
Airport.Name                          NaN
Injury.Severity                  Fatal(2)
Aircraft.damage                 Destroyed
Aircraft.Category                     NaN
Registration.Number                NC6404
Make                              Stinson
Model                               108-3
Amateur.Built                          No
Number.of.Engines                       1
Engine.Type                 Reciprocating
FAR.Description                       NaN
Schedule                              NaN
Purpose.of.flight                Personal
Air.carrier                           NaN
Total.Fatal.Injuries                    2
Total.Serious.Injuries                  0
Total.Minor.Injuries                    0
Total.Uninjured                         0
Weather.Condition                     UNK
Broad.phase.of.flight              Cruise
Report.Status              Probable Cause
Publication.Date                      NaN
Name: 0, dtype: object

### SAW A 'MAKE' COLUMN, PIQUED MY INTEREST

In [20]:
column_name = 'Make'

unique_inputs = df[column_name].unique()
num_unique_inputs = len(unique_inputs)

print("Unique inputs for the 'Make' column:")
print(unique_inputs)

print("Number of unique inputs for the 'Make' column:", num_unique_inputs)

Unique inputs for the 'Make' column:
['Stinson' 'Piper' 'Cessna' ... 'JAMES R DERNOVSEK' 'ORLICAN S R O'
 'ROYSE RALPH L']
Number of unique inputs for the 'Make' column: 8238

### FROM OUTSIDE RESEARCH, FOUND OUT THAT MOST COMMONLY USED COMMERCIAL PLANE TODAY IS THE 'BOEING 737 NEXT GENERATION', WHICH MADE ITS DEBUT IN 1997.

In [21]:
target_make = 'Boeing'

if target_make in unique_makes:
    print("'{}' is within the unique inputs for the '{}' column.".format(target_make, column_name))
else:
    print("'{}' is not found in the unique inputs for the '{}' column.".format(target_make, column_name))

'Boeing' is within the unique inputs for the 'Make' column.

### NOW I REMOVE ALL ENTRIES PRIOR TO 1997.

In [25]:
# convert to datetime just in case
df['Event.Date'] = pd.to_datetime(df['Event.Date'])

df = df[df['Event.Date'].dt.year >= 1997]

# reset the index to avoid complications
df = df.reset_index(drop = True)

df.head()

         Event.Id Investigation.Type Accident.Number Event.Date           Location        Country Latitude Longitude Airport.Code          Airport.Name Injury.Severity Aircraft.damage Aircraft.Category Registration.Number           Make      Model Amateur.Built  Number.of.Engines    Engine.Type FAR.Description Schedule Purpose.of.flight      Air.carrier  Total.Fatal.Injuries  Total.Serious.Injuries  Total.Minor.Injuries  Total.Uninjured Weather.Condition Broad.phase.of.flight   Report.Status Publication.Date
0  20001208X07301           Accident      IAD97FA038 1997-01-01      BITTINGER, MD  United States      NaN       NaN          NaN                   NaN        Fatal(1)       Destroyed               NaN              N8925S         Cessna       150F            No                1.0  Reciprocating             NaN      NaN          Personal              NaN                   1.0                     0.0                   0.0              0.0               IMC                Cruise  Probable Cause       30-10-1998
1  20001208X07265           Accident      CHI97LA049 1997-01-01    KANSAS CITY, MO  United States      NaN       NaN          MKC  KANSAS CITY DOWNTOWN       Non-Fatal     Substantial               NaN              N8040A  Gates Learjet       LR35            No                2.0      Turbo Fan             NaN     NSCH           Unknown  (dba: Us Check)                   0.0                     0.0                   0.0              2.0               IMC               Landing  Probable Cause       25-08-1997
2  20001208X07329           Accident      MIA97LA058 1997-01-01      KISSIMMEE, FL  United States      NaN       NaN          ISM             KISSIMMEE       Non-Fatal     Substantial               NaN              N14128           Waco      WMF-5            No                1.0  Reciprocating             NaN      NaN          Personal              NaN                   0.0                     0.0                   0.0              2.0               VMC               Landing  Probable Cause       25-08-1997
3  20001208X07327           Accident      MIA97LA055 1997-01-01       FLORENCE, SC  United States      NaN       NaN          NaN                   NaN       Non-Fatal     Substantial               NaN              N2205Z          Piper  PA-28-181            No                1.0  Reciprocating             NaN      NaN          Personal              NaN                   0.0                     3.0                   1.0              0.0               IMC              Approach  Probable Cause       25-08-1997
4  20001208X07326           Accident      MIA97LA054 1997-01-01  DAYTONA BEACH, FL  United States      NaN       NaN          DAB   DAYTONA BEACH INT'L       Non-Fatal     Substantial               NaN              N5813G         Cessna       150K            No                1.0  Reciprocating             NaN      NaN          Personal              NaN                   0.0                     2.0                   0.0              0.0               VMC               Takeoff  Probable Cause       30-09-1997

### NOW I DELVE INTO 'Amateur.Built' COLUMN AND SUBSEQUENTLY REMOVE ALL AMATEUR-BUILT MACHINES

In [35]:
column_name = 'Amateur.Built'

unique_inputs = df[column_name].unique()
num_unique_inputs = len(unique_inputs)

print("Unique inputs for the 'Make' column:")
print(unique_inputs)

print("Number of unique inputs for the 'Make' column:", num_unique_inputs)

Unique inputs for the 'Make' column:
['No' nan]
Number of unique inputs for the 'Make' column: 2

In [30]:
df = df[df['Amateur.Built'] != 'Yes']

df.head()

         Event.Id Investigation.Type Accident.Number Event.Date           Location        Country Latitude Longitude Airport.Code          Airport.Name Injury.Severity Aircraft.damage Aircraft.Category Registration.Number           Make      Model Amateur.Built  Number.of.Engines    Engine.Type FAR.Description Schedule Purpose.of.flight      Air.carrier  Total.Fatal.Injuries  Total.Serious.Injuries  Total.Minor.Injuries  Total.Uninjured Weather.Condition Broad.phase.of.flight   Report.Status Publication.Date
0  20001208X07301           Accident      IAD97FA038 1997-01-01      BITTINGER, MD  United States      NaN       NaN          NaN                   NaN        Fatal(1)       Destroyed               NaN              N8925S         Cessna       150F            No                1.0  Reciprocating             NaN      NaN          Personal              NaN                   1.0                     0.0                   0.0              0.0               IMC                Cruise  Probable Cause       30-10-1998
1  20001208X07265           Accident      CHI97LA049 1997-01-01    KANSAS CITY, MO  United States      NaN       NaN          MKC  KANSAS CITY DOWNTOWN       Non-Fatal     Substantial               NaN              N8040A  Gates Learjet       LR35            No                2.0      Turbo Fan             NaN     NSCH           Unknown  (dba: Us Check)                   0.0                     0.0                   0.0              2.0               IMC               Landing  Probable Cause       25-08-1997
2  20001208X07329           Accident      MIA97LA058 1997-01-01      KISSIMMEE, FL  United States      NaN       NaN          ISM             KISSIMMEE       Non-Fatal     Substantial               NaN              N14128           Waco      WMF-5            No                1.0  Reciprocating             NaN      NaN          Personal              NaN                   0.0                     0.0                   0.0              2.0               VMC               Landing  Probable Cause       25-08-1997
3  20001208X07327           Accident      MIA97LA055 1997-01-01       FLORENCE, SC  United States      NaN       NaN          NaN                   NaN       Non-Fatal     Substantial               NaN              N2205Z          Piper  PA-28-181            No                1.0  Reciprocating             NaN      NaN          Personal              NaN                   0.0                     3.0                   1.0              0.0               IMC              Approach  Probable Cause       25-08-1997
4  20001208X07326           Accident      MIA97LA054 1997-01-01  DAYTONA BEACH, FL  United States      NaN       NaN          DAB   DAYTONA BEACH INT'L       Non-Fatal     Substantial               NaN              N5813G         Cessna       150K            No                1.0  Reciprocating             NaN      NaN          Personal              NaN                   0.0                     2.0                   0.0              0.0               VMC               Takeoff  Probable Cause       30-09-1997

### ENGINE TIMEEEEEE! IDENTIFY UNIQUE ENGINE TYPES AND DROP ALL THE ONES THAT AREN'T USED BY COMMERCIAL AIRPLANES (involes outside research)

In [40]:
column_name = 'Engine.Type'

unique_inputs = df[column_name].unique()
num_unique_inputs = len(unique_inputs)

print("Unique inputs for the 'Make' column:")
print(unique_inputs)

print("Number of unique inputs for the 'Make' column:", num_unique_inputs)

Unique inputs for the 'Make' column:
['Reciprocating' 'Turbo Fan' 'Turbo Prop' 'Turbo Shaft' 'Turbo Jet'
 'Unknown' nan 'None' 'Electric' 'Hybrid Rocket' 'Geared Turbofan' 'LR'
 'UNK' 'NONE']
Number of unique inputs for the 'Make' column: 14

In [37]:
column_name = 'Number.of.Engines'

unique_inputs = df[column_name].unique()
num_unique_inputs = len(unique_inputs)

print("Unique inputs for the 'Make' column:")
print(unique_inputs)

print("Number of unique inputs for the 'Make' column:", num_unique_inputs)

Unique inputs for the 'Make' column:
[ 1.  2. nan  3.  4.  0.  8.  6.]
Number of unique inputs for the 'Make' column: 8

In [44]:
inputs_to_drop = ['Turbo Shaft', 'Reciprocating', 'Electric', 'Hybrid Rocket']

# drop rows with the specified inputs in 'Engine.Type' column
df = df[~df['Engine.Type'].isin(inputs_to_drop)]

df.head()

          Event.Id Investigation.Type Accident.Number Event.Date             Location        Country Latitude Longitude Airport.Code              Airport.Name Injury.Severity Aircraft.damage Aircraft.Category Registration.Number           Make     Model Amateur.Built  Number.of.Engines Engine.Type FAR.Description Schedule Purpose.of.flight                              Air.carrier  Total.Fatal.Injuries  Total.Serious.Injuries  Total.Minor.Injuries  Total.Uninjured Weather.Condition Broad.phase.of.flight   Report.Status Publication.Date
1   20001208X07265           Accident      CHI97LA049 1997-01-01      KANSAS CITY, MO  United States      NaN       NaN          MKC      KANSAS CITY DOWNTOWN       Non-Fatal     Substantial               NaN              N8040A  Gates Learjet      LR35            No                2.0   Turbo Fan             NaN     NSCH           Unknown                          (dba: Us Check)                   0.0                     0.0                   0.0              2.0               IMC               Landing  Probable Cause       25-08-1997
6   20001208X07328           Accident      MIA97LA056 1997-01-02         LAKELAND, FL  United States      NaN       NaN          LAL  LAKELAND LINDER REGIONAL       Non-Fatal       Destroyed               NaN              N441MS         Cessna       441            No                2.0  Turbo Prop             NaN      NaN           Unknown                                      NaN                   0.0                     0.0                   2.0              0.0               VMC               Takeoff  Probable Cause       01-08-2001
7   20001208X07322           Accident      MIA97FA057 1997-01-02          EDENTON, NC  United States      NaN       NaN          EDE     NORTHEASTERN REGIONAL        Fatal(2)       Destroyed               NaN              N802TH         Cessna      208B            No                1.0  Turbo Prop             NaN      NaN       Positioning                                      NaN                   2.0                     0.0                   0.0              0.0               IMC              Approach  Probable Cause       10-04-1998
10  20001208X07281           Accident      FTW97LA074 1997-01-02  RIO GRANDE CITY, TX  United States      NaN       NaN          NaN                       NaN       Non-Fatal     Substantial               NaN              N1552D          Beech      C90A            No                2.0  Turbo Prop             NaN      NaN          Business                                      NaN                   0.0                     0.0                   0.0              1.0               VMC              Approach  Probable Cause       25-08-1997
18  20001208X07308           Accident      LAX97FA082 1997-01-05    BULLHEAD CITY, AZ  United States      NaN       NaN          NaN                       NaN       Non-Fatal       Destroyed               NaN              N165SW      Fairchild  SA227-AC            No                2.0  Turbo Prop             NaN     NSCH           Unknown  Fng Aviation Inc (dba: Skylink Charter)                   0.0                     0.0                   2.0             19.0               VMC                Cruise  Probable Cause       25-03-1998